name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # A animação será atualizada todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: PauloJose-PJ
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
